=== loye168/tddl5/trunk/alibaba/tddl5/tddl-common/src/main/resources/META-INF/matrix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://github.com/tddl/tddl/schema/matrix"
	xmlns="https://github.com/tddl/tddl/schema/matrix" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

    <xs:element name="matrix">
		<xs:annotation>
			<xs:documentation>matrix config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="group" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="properties" minOccurs="0" maxOccurs="1" />
				<xs:element name="appName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="group">
		<xs:annotation>
			<xs:documentation>group config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="atom" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="properties" minOccurs="0" maxOccurs="1" />
			</xs:choice>

			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			
			<xs:attribute name="type" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="atom">
		<xs:annotation>
			<xs:documentation>atom config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="properties" minOccurs="0" maxOccurs="1" />
			</xs:choice>

			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="properties">
		<xs:annotation>
			<xs:documentation>properties config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>property config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>property name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string">
				<xs:annotation>
					<xs:documentation>property value</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-optimizer/src/test/resources/config/test_matrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix xmlns="https://github.com/tddl/tddl/schema/matrix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">
    
    <appName>test_matrix</appName>
    
	<group name="andor_group_0" type="MYSQL_JDBC">
	</group>

	<group name="andor_group_1" type="MYSQL_JDBC">
	</group>
	
	<!-- hbase group -->
	<group name="andor_hbase_group" type="HBASE_CLIENT">
		<properties>
			<property name="mysql_groupName">
				<value>andor_hbase_group</value>
			</property>
			<property name="mysql_appName" value="andor_hbase_qatest" />
			<property name="hbase.zookeeper.quorum" value="10.20.144.51" />
			<property name="hbase.zookeeper.property.clientPort" value="2181" />
			<property name="zookeeper.znode.parent" value="/hbase_tesla" />
		</properties>
	</group>

	<group name="andor_hbase_group2" type="HBASE_CLIENT">
		<properties>
			<property name="mysql_groupName" value="andor_hbase_group2" />
			<property name="mysql_appName" value="andor_hbase_qatest" />
			<property name="hbase.zookeeper.quorum" value="10.232.98.74,10.232.98.75,10.232.98.76,10.232.98.77,10.232.98.7" />
			<property name="hbase.zookeeper.property.clientPort" value="2181" />
			<property name="zookeeper.znode.parent" value="/hbase-rd-test-0.94" />
		</properties>
	</group>
</matrix>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-qatest/src/test/resources/test_matrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix xmlns="https://github.com/tddl/tddl/schema/matrix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">

	<appName>andor_show</appName>
	<group name="andor_show_group0" type="MYSQL_JDBC">
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_show_group0">
				<value>andor_show_group0_atom0:r10w10p0</value>
			</property>
		</properties>

		<atom name="andor_show_group0_atom0">
			<properties>
				<property name="com.taobao.tddl.atom.global.andor_show_group0_atom0">
					<value>
					ip=10.232.31.21
					port=3306
					dbName=andor_show
					dbType=mysql
					dbStatus=RW
				</value>
				</property>
				<property
					name="com.taobao.tddl.atom.app.andor_show.andor_show_group0_atom0">
					<value>
					userName=andor
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
				</value>
				</property>

				<property name="com.taobao.tddl.atom.passwd.andor_show.mysql.andor">
					<value>encPasswd=andor</value>
				</property>
			</properties>
		</atom>

		<atom name="">
		</atom>

		<atom name="">
		</atom>
	</group>


	<group name="andor_show_group1" type="MYSQL_JDBC">
	</group>

	<group name="ob_group" type="OCEANBASE_JDBC">
		<properties>
			<property name="CONFIGURL">
				<value>http://obconsole.test.alibaba-inc.com/ob-config/config.co?dataId=wireless_message</value>
			</property>
		</properties>
	</group>
</matrix>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-sample/src/main/resources/sample_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix xmlns="https://github.com/tddl/tddl/schema/matrix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">
	<appName>tddl5_sample</appName>
	

	<group name="tddl5_sample_group" type="MYSQL_JDBC">


		<!-- group config -->
		<properties>

			<!-- group r/w weight,format is : com.taobao.tddl.jdbc.group_V2.4.1_{group_name} -->
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_tddl5_sample_group">
				<value>tddl5_sample_group_atom0:r10w10p0</value>
			</property>
		</properties>

		<!-- atom config in this group -->
		<atom name="tddl5_sample_group_atom0">
			<properties>

				<!-- global atom config, format is : com.taobao.tddl.atom.global.{atom_name} -->
				<property name="com.taobao.tddl.atom.global.tddl5_sample_group_atom0">
					<value>
						ip=127.0.0.1
						port=3306
						dbName=tddl_sample
						dbType=mysql
						dbStatus=RW
					</value>
				</property>
				
				<!-- app atom config, format is :  com.taobao.tddl.atom.app.{app_name}.{atom_name} -->
				<property
					name="com.taobao.tddl.atom.app.tddl5_sample.tddl5_sample_group_atom0">
					<value>
						userName=root
						minPoolSize=20
						maxPoolSize=40
						idleTimeout=20
						blockingTimeout=10000
						preparedStatementCacheSize=1000
						connectionProperties=characterEncoding=gbk;autoReconnect=true
						readRestrictTimes=0
						writeRestrictTimes=0
						timeSliceInMillis=0
					</value>
				</property>
				<!-- atom password , format is : com.taobao.tddl.atom.passwd.{db_name}.mysql.{user_name} -->
				<property name="com.taobao.tddl.atom.passwd.tddl_sample.mysql.root">
					<value>root</value>
				</property>
			</properties>
		</atom>
	</group>
	
	<group name="demo_group" type="demo">

	</group>
</matrix>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-qatest/src/test/resources/matrix/server_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix xmlns="https://github.com/tddl/tddl/schema/matrix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">
	
	<properties>
		<property name="com.taobao.tddl.v1_andor_mysql_qatest_tddlconfig" value="" />
	</properties>
	
	<!-- mysql group -->
	<group name="andor_mysql_group_0" type="MYSQL_JDBC">
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_mysql_group_0">
				<value>andor_mysql_group_0_atom0:r10w10p0</value>
			</property>
			<property name="com.taobao.tddl.jdbc.extra_config.group_V2.4.1_andor_mysql_group_0.andor_mysql_qatest">
				<value>
					{"sqlForbid":[],"sqlDsIndex":{},"tabDsIndex":{},"defaultMain":"true"}
				</value>
			</property>
		</properties>
		
		<atom name="andor_mysql_group_0_atom0">
			<properties>
				<property name="com.taobao.tddl.atom.global.andor_mysql_group_0_atom0">
					<value>
					ip=10.232.24.104
					port=3306
					dbName=andor_mysql_group_0_atom0
					dbType=mysql
					dbStatus=RW
					</value>
				</property>
				<property name="com.taobao.tddl.atom.app.andor_mysql_qatest.andor_mysql_group_0_atom0">
					<value>
					userName=diamond
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
					</value>
				</property>

				<property name="com.taobao.tddl.atom.passwd.andor_mysql_group_0_atom0.mysql.diamond">
					<value>encPasswd=-6e3251280f47bc7d</value>
				</property>
			</properties>
		</atom>
	</group>

	<group name="andor_mysql_group_1" type="MYSQL_JDBC" >
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_mysql_group_1">
				<value>andor_mysql_group_1_atom0:r10w10p0</value>
			</property>
			<property name="com.taobao.tddl.jdbc.extra_config.group_V2.4.1_andor_mysql_group_1.andor_mysql_qatest">
				<value>
					{"sqlForbid":[],"sqlDsIndex":{},"tabDsIndex":{},"defaultMain":"true"}
				</value>
			</property>
		</properties>
		
		<atom name="andor_mysql_group_1_atom0">
			<properties>
				<property name="com.taobao.tddl.atom.global.andor_mysql_group_1_atom0">
					<value>
					ip=10.232.24.104
					port=3306
					dbName=andor_mysql_group_1_atom0
					dbType=mysql
					dbStatus=RW
					</value>
				</property>
				<property name="com.taobao.tddl.atom.app.andor_mysql_qatest.andor_mysql_group_1_atom0">
					<value>
					userName=diamond
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
					</value>
				</property>
				<property name="com.taobao.tddl.atom.passwd.andor_mysql_group_1_atom0.mysql.diamond">
					<value>encPasswd=-6e3251280f47bc7d</value>
				</property>
			</properties>
		</atom>
	</group>

	<group name="andor_mysql_group_2" type="MYSQL_JDBC">
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_mysql_group_2">
				<value>andor_mysql_group_2_atom0:r10w10p0</value>
			</property>
			<property name="com.taobao.tddl.jdbc.extra_config.group_V2.4.1_andor_mysql_group_2.andor_mysql_qatest">
				<value>
					{"sqlForbid":[],"sqlDsIndex":{},"tabDsIndex":{},"defaultMain":"true"}
				</value>
			</property>
		</properties>
		
		<atom name="andor_mysql_group_2_atom0">
			<properties>
				<property name="com.taobao.tddl.atom.global.andor_mysql_group_2_atom0">
					<value>
					ip=10.232.24.104
					port=3306
					dbName=andor_mysql_group_2_atom0
					dbType=mysql
					dbStatus=RW
					</value>
				</property>
				<property name="com.taobao.tddl.atom.app.andor_mysql_qatest.andor_mysql_group_2_atom0">
					<value>
					userName=diamond
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
					</value>
				</property>

				<property name="com.taobao.tddl.atom.passwd.andor_mysql_group_2_atom0.mysql.diamond">
					<value>encPasswd=-6e3251280f47bc7d</value>
				</property>
			</properties>
		</atom>
	</group>
	
	<group name="andor_mysql_group_oneAtom" type="MYSQL_JDBC">
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_mysql_group_oneAtom">
				<value>andor_mysql_group_atom:r10w10p0</value>
			</property>
			<property name="com.taobao.tddl.jdbc.extra_config.group_V2.4.1_andor_mysql_group_oneAtom.andor_mysql_qatest">
				<value>
					{"sqlForbid":[],"sqlDsIndex":{},"tabDsIndex":{},"defaultMain":"true"}
				</value>
			</property>
		</properties>
		
		<atom name="andor_mysql_group_atom">
			<properties>
				<property name="com.taobao.tddl.atom.global.andor_mysql_group_atom">
					<value>
					ip=10.232.24.104
					port=3306
					dbName=andor_mysql_group_atom
					dbType=mysql
					dbStatus=RW
					</value>
				</property>
				<property name="com.taobao.tddl.atom.app.andor_mysql_qatest.andor_mysql_group_atom">
					<value>
					userName=diamond
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
					</value>
				</property>

				<property name="com.taobao.tddl.atom.passwd.andor_mysql_group_atom.mysql.diamond">
					<value>encPasswd=-6e3251280f47bc7d</value>
				</property>
			</properties>
		</atom>
	</group>
	
	<group name="ob_group_oneAtom" type="OCEANBASE_JDBC">
		<properties>
			<property name="CONFIGURL">
				<value>http://obconsole.test.alibaba-inc.com/ob-config/config.co?dataId=wireless_message</value>
			</property>
		</properties>
	</group>
	
	<group name="demo_group" type="demo">

	</group>
	
	<!-- hbase group 
	<group name="andor_hbase_group" type="HBASE_CLIENT">
		<properties>
				<property name="hbase.zookeeper.quorum" value="10.20.144.51" />
				<property name="hbase.zookeeper.property.clientPort" value="2181" />
				<property name="zookeeper.znode.parent" value="/hbase_tesla" />
		</properties>
	</group>


	<group name="andor_hbase_group2" type="HBASE_CLIENT"
		>
		<properties>
				<property name="hbase.zookeeper.quorum" value="10.232.98.74,10.232.98.75,10.232.98.76,10.232.98.77,10.232.98.7" />
				<property name="hbase.zookeeper.property.clientPort" value="2181" />
				<property name="zookeeper.znode.parent" value="/hbase-rd-test-0.94" />
		</properties>
	</group>
	-->
</matrix>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-sample/src/main/resources/topology_DEV_SUBWAY_MYSQL.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<matrix xmlns="https://github.com/tddl/tddl/schema/matrix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">
<appName>DEV_SIMBA2_DB</appName>
<group name="SUBWAY_DEV_G_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P00_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P01_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P02_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P03_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P04_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P05_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P06_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P07_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P08_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P09_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P10_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P11_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P12_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P13_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P14_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P15_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P16_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P17_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P18_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P19_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P20_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P21_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P22_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P23_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P24_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P25_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P26_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P27_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P28_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P29_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P30_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_DEV_P31_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ0_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ1_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ2_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ3_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ4_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ5_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ6_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ7_GROUP" type="MYSQL_JDBC"/>
<group name="ob_group" type="OCEANBASE_JDBC">
		<properties>
			<property name="CONFIGURL">
				<value>http://obconsole.test.alibaba-inc.com/ob-config/config.co?dataId=wireless_message</value>
			</property>
		</properties>
	</group>
</matrix>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-sample/src/main/resources/topology_DEV_SIMBA2_MYSQL.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<matrix xmlns="https://github.com/tddl/tddl/schema/matrix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">
<appName>DAILY_SOLAR_MERCURY_APP</appName>
<group name="SOLAR_MERCURY_G_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P00_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P01_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P02_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P03_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P04_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P05_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P06_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P07_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P08_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P09_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P10_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P11_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P12_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P13_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P14_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P15_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P16_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P17_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P18_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P19_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P20_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P21_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P22_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P23_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P24_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P25_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P26_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P27_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P28_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P29_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P30_GROUP" type="MYSQL_JDBC"/>
<group name="SOLAR_MERCURY_P31_GROUP" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ0_GROUP1" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ1_GROUP1" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ2_GROUP1" type="MYSQL_JDBC"/>
<group name="SUBWAY_SEQ3_GROUP1" type="MYSQL_JDBC"/>

<group name="ob_group" type="OCEANBASE_JDBC">
		<properties>
			<property name="CONFIGURL">
				<value>http://obconsole.test.alibaba-inc.com/ob-config/config.co?dataId=wireless_message</value>
			</property>
		</properties>
	</group>
</matrix>
