=== loye168/tddl5/trunk/alibaba/tddl5/tddl-common/src/main/resources/META-INF/stat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://github.com/tddl/tddl/schema/stat" xmlns="https://github.com/tddl/tddl/schema/stat" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="tableStats">
        <xs:annotation>
        	<xs:documentation>tableStats config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
            	<xs:element ref="tableStat" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="tableStat">
        <xs:annotation>
        	<xs:documentation>tableStat config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
            	<xs:element ref="tableName" maxOccurs="1" />
            	<xs:element ref="tableRows" maxOccurs="1" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
	
	<xs:element name="tableIndexStats">
        <xs:annotation>
        	<xs:documentation>KVIndexStats config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
            	<xs:element ref="tableIndexStat" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="tableIndexStat">
		<xs:annotation>
			<xs:documentation>KVIndexStat config</xs:documentation>
		</xs:annotation>
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="tableName" maxOccurs="1" />
        		<xs:element ref="indexStats" maxOccurs="1" />
        	</xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="tableName" type="xs:string">
        <xs:annotation>
        	<xs:documentation>tableName config</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:element name="tableRows" type="xs:string">
        <xs:annotation>
        	<xs:documentation>tableRows config</xs:documentation>
        </xs:annotation>
    </xs:element>
    
     <xs:element name="indexStats">
        <xs:annotation>
        	<xs:documentation>KVIndexStats config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="indexStat" maxOccurs="unbounded" />
        	</xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="indexStat">
        <xs:complexType>
       		<xs:choice maxOccurs="unbounded">
	        	<xs:element name="indexName" type="xs:string" >
	        		<xs:annotation>
	        			<xs:documentation>index name</xs:documentation>
	        		</xs:annotation>
	        	</xs:element>
	        	<xs:element name="indexType" type="xs:string" >
        		<xs:annotation>
        			<xs:documentation>index type</xs:documentation>
        		</xs:annotation>
	        	</xs:element>
	        	<xs:element name="distinctKeys" type="xs:string" >
	        		<xs:annotation>
	        			<xs:documentation>distinct keys</xs:documentation>
	        		</xs:annotation>
	        	</xs:element>
	        	<xs:element name="numRows" type="xs:string" >
	        		<xs:annotation>
	        			<xs:documentation>num rows</xs:documentation>
	        		</xs:annotation>
	        	</xs:element>
	        	<xs:element name="factor" type="xs:string">
	        		<xs:annotation>
	        			<xs:documentation>factor</xs:documentation>
	        		</xs:annotation>
	        	</xs:element>
        	</xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-optimizer/src/test/resources/config/kvIndex_stat.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tableIndexStats xmlns="https://github.com/tddl/tddl/schema/stat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/tddl/tddl/schema/stat https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/stat.xsd">
	<tableIndexStat>
		<tableName>TABLE1</tableName>
		<indexStats>
			<indexStat>
				<indexName>TABLE1._ID</indexName>
				<indexType>0</indexType>
				<distinctKeys>100000</distinctKeys>
				<numRows>100000</numRows>
				<factor>1.0</factor>
			</indexStat>
			<indexStat>
				<indexName>TABLE1._NAME</indexName>
				<indexType>0</indexType>
				<distinctKeys>1000</distinctKeys>
				<numRows>100000</numRows>
				<factor>0.01</factor>
			</indexStat>
		</indexStats>
	</tableIndexStat>
	<tableIndexStat>
		<tableName>TABLE2</tableName>
		<indexStats>
			<indexStat>
				<indexName>TABLE2._ID</indexName>
				<indexType>0</indexType>
				<distinctKeys>100000</distinctKeys>
				<numRows>100000</numRows>
				<factor>1.0</factor>
			</indexStat>
			<indexStat>
				<indexName>TABLE2._NAME</indexName>
				<indexType>0</indexType>
				<distinctKeys>1000</distinctKeys>
				<numRows>100000</numRows>
				<factor>0.01</factor>
			</indexStat>
		</indexStats>
	</tableIndexStat>
	
	<tableIndexStat>
		<tableName>TABLE3</tableName>
		<indexStats>
			<indexStat>
				<indexName>TABLE3._ID</indexName>
				<indexType>0</indexType>
				<distinctKeys>1000</distinctKeys>
				<numRows>1000</numRows>
				<factor>1.0</factor>
			</indexStat>
		</indexStats>
	</tableIndexStat>
</tableIndexStats>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-optimizer/src/test/resources/config/table_stat.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tableStats xmlns="https://github.com/tddl/tddl/schema/stat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/tddl/tddl/schema/stat https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/stat.xsd">
	<tableStat>
		<tableName>TABLE1</tableName>
		<tableRows>1000</tableRows>
	</tableStat>
	<tableStat>
		<tableName>TABLE2</tableName>
		<tableRows>100000</tableRows>
	</tableStat>
	<tableStat>
		<tableName>TABLE3</tableName>
		<tableRows>999</tableRows>
	</tableStat>
</tableStats>
