=== loye168/tddl5/trunk/alibaba/tddl5/tddl-common/src/main/resources/META-INF/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://github.com/tddl/tddl/schema/table" xmlns="https://github.com/tddl/tddl/schema/table" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="tables">
        <xs:annotation>
        	<xs:documentation>tables config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
            	<xs:element ref="table" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="table">
		<xs:annotation>
			<xs:documentation>table config</xs:documentation>
		</xs:annotation>
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="columns" maxOccurs="1" />
        		<xs:element ref="primaryKey" maxOccurs="1" />
        		<xs:element ref="partitionColumns" maxOccurs="1" />
        		<xs:element ref="secondaryIndexes" maxOccurs="1" />
        	</xs:choice>
        	<xs:attribute name="name" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>table name</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="columns">
        <xs:annotation>
        	<xs:documentation>columns config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        	<xs:sequence>
        		<xs:element ref="column" minOccurs="1" maxOccurs="unbounded" />
        	</xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="column">
        <xs:complexType>
        	<xs:attribute name="name" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>column name</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="type" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>column type</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="alias" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>column alias</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="nullable" type="xs:boolean" use="optional" default="true">
        		<xs:annotation>
        			<xs:documentation>column nullable</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="auto_increment" type="xs:boolean" use="optional" default="false">
        		<xs:annotation>
        			<xs:documentation>column auto increment</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="primaryKey" type="xs:string" />
    
    <xs:element name="secondaryIndexes">
        <xs:annotation>
        	<xs:documentation>secondary indexes config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="indexMeta" maxOccurs="unbounded" />
        	</xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="indexMeta">
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="keys" maxOccurs="1" />
        		<xs:element ref="values" maxOccurs="1" />
        		<xs:element ref="partitionColumns" maxOccurs="1" />
        	</xs:choice>
        	<xs:attribute name="name" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>column name</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="type" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>column type</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="strongConsistent" type="xs:boolean" use="optional" >
        		<xs:annotation>
        			<xs:documentation>column type</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="keys" type="xs:string">
        <xs:annotation>
        	<xs:documentation>secondary indexes keys config</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:element name="values" type="xs:string">
        <xs:annotation>
        	<xs:documentation>secondary indexes values config</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:element name="partitionColumns" type="xs:string">
        <xs:annotation>
        	<xs:documentation>secondary indexes partitionColumns config</xs:documentation>
        </xs:annotation>
    </xs:element>
</xs:schema>

=== loye168/tddl5/trunk/alibaba/tddl5/tddl-sample/src/main/resources/test_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="https://github.com/tddl/tddl/schema/table" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/tddl/tddl/schema/table https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/table.xsd">
    
	<table name="adam_stream_sample_collect">
		<columns>
			<column name="id" type="long"/>
			<column name="gmt_create" type="datetime"/>
			<column name="gmt_modified" type="datetime"/>
			<column name="date_time" type="datetime"/>
			<column name="data_value" type="long"/>
			<column name="index_id" type="long"/>
			<column name="report_time" type="datetime"/>
			<column name="dimension_value" type="string"/>
			<column name="combine_key" type="string"/>
		</columns>
		<primaryKey>id</primaryKey>
	</table>
	
	
</tables>
